name: ravens_nest
description: "A Flutter condo management application converted from React."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  fl_chart: ^1.0.0
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
