name: ravens_nest
description: "A Flutter condo management application converted from React."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  fl_chart: ^1.1.0
  supabase_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
