// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtAa6znwld6hJdlBdDEPhqkECzuuyzzo8',
    appId: '1:152637585017:web:ec43d14d9b3224963386a8',
    messagingSenderId: '152637585017',
    projectId: 'missing-person-cap',
    authDomain: 'missing-person-cap.firebaseapp.com',
    storageBucket: 'missing-person-cap.firebasestorage.app',
    measurementId: 'G-KW3Q9T21GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOEjzw3xPeciieI8-u2B1SZIDFGnsl2Xo',
    appId: '1:152637585017:android:74e225bfa99f64353386a8',
    messagingSenderId: '152637585017',
    projectId: 'missing-person-cap',
    storageBucket: 'missing-person-cap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA-UmuvfDALwwL6Etu0HyW8MhVZyuKGJU',
    appId: '1:152637585017:ios:e1ec57f7f58fab5e3386a8',
    messagingSenderId: '152637585017',
    projectId: 'missing-person-cap',
    storageBucket: 'missing-person-cap.firebasestorage.app',
    iosClientId: '152637585017-3knoqmn9oec9sh7e1l4f3tip6tsv2nbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.findlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA-UmuvfDALwwL6Etu0HyW8MhVZyuKGJU',
    appId: '1:152637585017:ios:e1ec57f7f58fab5e3386a8',
    messagingSenderId: '152637585017',
    projectId: 'missing-person-cap',
    storageBucket: 'missing-person-cap.firebasestorage.app',
    iosClientId: '152637585017-3knoqmn9oec9sh7e1l4f3tip6tsv2nbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.findlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtAa6znwld6hJdlBdDEPhqkECzuuyzzo8',
    appId: '1:152637585017:web:a1bc867718b91b373386a8',
    messagingSenderId: '152637585017',
    projectId: 'missing-person-cap',
    authDomain: 'missing-person-cap.firebaseapp.com',
    storageBucket: 'missing-person-cap.firebasestorage.app',
    measurementId: 'G-KW3Q9T21GY',
  );

}